### ISSUE TITLE
Big 'translate arrows' and 'rotate orbs' and Cura crashes

### ISSUE THREAD

**Issue by Jerooney** [Kriechi/Cura-DuetRRFPlugin#47]
Dear contributor,

I write this error report based on a support case received by the Ultimaker team.
The customer faced graphical issues, as attached.
These graphical issues were resolved when uninstalling this plugin.
![Graphical_arrow](https://user-images.githubusercontent.com/20047496/223045662-d5ba3a2a-7538-498c-b783-dad825f08f19.png)
![Graphical_orb](https://user-images.githubusercontent.com/20047496/223045668-09760b44-b0e8-4c72-a107-418833e84aed.png)

His Ultimaker Cura 5.2.1 application crashed within 1-2 minutes, when setting up a simple 'test print cube', and Cura was unusable.
We cannot guarantee if other plugins conflicted and caused issues. The customers does claim, his other plugins are re-installed and Cura is working fine! (log file attached)
[cura_duet_plugin.log](https://github.com/Kriechi/Cura-DuetRRFPlugin/files/10895396/cura_duet_plugin.log)

**Original message from customer, after troubleshooting:**
_So I looked and I have the following plugins:
- Arc Welder
- Duet RepRap Firmware Integration
- Material Settings
- Mesh Tools
- Settings Guide
- Startup Optimizer

I started Cura and brought in a STL file, saved it, and had the graphics error.
I then uninstalled the following plug-ins, one at a time, retrying the exact same part with no other changes. Yes Cura was restarted after each uninstall.

#1 Mesh Tools: Still had error.
#2 Material Settings: Still had error.
#3 Arc Welder: Still had error.
#4 Duet RepRap Firmware Integration: Error did not happen.

I then reinstalled the Duet RepRap Firmware Integration and the error came back.
I then uninstalled the Duet RepRap Firmware Integration and the error did not happen._

**Comment by Kriechi** [comment]
Hi @Jerooney!

could you please confirm if we are talking about graphical glitches or full crashes in this case? From your message I'm not sure, as you (or the support case you received) first mentions "application crashed within 1-2 minutes" and then later only describe "graphics error".

From the attached log file, I cannot find any crash reports or exception handling, apart from one entry related to `UM.FileHandler.WriteFileJob.WriteFileJob` and `JobQueueWorker` -- both are unrelated to the DuetRRF plugin.

About the potential graphics errors: I'm not aware of any functionality in the DuetRRF plugin that is interfacing with the rendering of the scene in any way -- so I'm surprised to get such a report. Can you please attach a screenshot of the scene *with* and *without* the plugin installed to compare the two?

From the attached log file, I can see that Cura was restarted multiple times, but always with the DuetRRF plugin installed and loaded successfully. I cannot see a start-up without the plugin, as claimed to be the fix for the graphics error.

Also, please update to the most recent stable release, currently Cura v5.2.2.

**Comment by Jerooney** [comment]
Hi @Kriechi !
I have checked with the original complaint, and it states:
"The graphical issue was so bad, I needed to manually shut down Cura after 1-2minutes, because the graphical glitch was emerging quickly after zooming and rotating the camera. After the glitch, it no longer allowed to prepare my print project."

So to remove any confusion: It seems that Cura does **not** crash from this issue!

The log file: This is correct, I have not received a 'new' log file after removal of the plugins. So the log file is 'old', but certainly contains the graphical issue in every boot.

The customer did not specifically send screenshots without the glitch, however, the arrows should be significantly smaller of course, in range with the other scaling of the UI elements.

I'm unsure if there's anything specific in play with the customers CPU/GPU or scaling factor in Windows,
Maybe it's best to keep this here as a piece of evidence, in the case more reports might come in.

The customer is aware of the 5.2.2 version, but decided to not use the plugin for now.
